services:
  orderservice:
    image: orderservice 
    build: .
    container_name: orderservice
    ports:
      - "3017:3017"
    environment:
      - ASPNETCORE_URLS=http://+:3017
      - DB_USER=sa
      - DB_PASSWORD=Your_password123
      - DB_SERVER=mssql
      - DB_DATABASE=tradeportdb
    networks:
      - my_network

networks:
  my_network:
    external: true
