# services:
#   orderservice:
#     image: orderservice 
#     build: .
#     container_name: orderservice
#     ports:
#       - "3017:3017"
#     environment:
#       - ASPNETCORE_URLS=http://+:3017
#       - DB_USER=sa
#       - DB_PASSWORD=Your_password123
#       - DB_SERVER=mssql
#       - DB_DATABASE=tradeportdb
#     networks:
#       - my_network

# networks:
#   my_network:
#     external: true

services:
  orderservice:
    build:
      context: ..
      dockerfile: OrderManagement/Dockerfile   # Path to your existing Dockerfile
    container_name: orderservice
    environment:
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "3017:80"
    networks:
      - my_network

networks:
  my_network:
    external: true

